# Generated by Django 2.0.1 on 2018-01-28 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Balance')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='wallet_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_from', to='wallet.Wallet'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='wallet_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_to', to='wallet.Wallet'),
        ),
    ]
